# Generated by Django 5.2 on 2025-05-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCardDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardDsgBizId', models.IntegerField(blank=True, null=True, verbose_name='Business ID')),
                ('CardDsgDesignTemplateId', models.CharField(blank=True, max_length=255, null=True)),
                ('CardDsgAddLogo', models.TextField(blank=True, null=True)),
                ('CardDsgBackgroundColor', models.CharField(blank=True, default='#FFFFFF', max_length=20, null=True)),
                ('CardDsgCreationDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('CardDsgTextColor', models.CharField(blank=True, default='#000000', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessRewardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RewardRuleBizId', models.IntegerField(verbose_name='Business ID')),
                ('RewardRuleType', models.CharField(choices=[('percentage', 'Percentage'), ('purchase_value_to_points', 'Purchase Value to Points'), ('flat', 'Flat')], max_length=30, verbose_name='Reward Rule Type')),
                ('RewardRuleNotionalValue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Notional Value')),
                ('RewardRuleValue', models.FloatField(blank=True, default=1.0, null=True, verbose_name='Reward Rule Value')),
                ('RewardRuleValidityPeriodYears', models.IntegerField(blank=True, null=True, verbose_name='Validity Period (years)')),
                ('RewardRuleMilestone', models.IntegerField(blank=True, null=True, verbose_name='Milestone (Points)')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('UpdatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrdTrnsBizId', models.IntegerField(verbose_name='Business ID')),
                ('CrdTrnsCardNumber', models.BigIntegerField(verbose_name='Card Number')),
                ('CrdTrnsPurchaseAmount', models.FloatField(verbose_name='Purchase Amount')),
                ('CrdTrnsPoint', models.PositiveIntegerField(blank=True, null=True, verbose_name='Transaction Points')),
                ('CrdTrnsTransactionType', models.CharField(choices=[('Points_Earned', 'Points Earned'), ('Points_Redeemed', 'Points Redeemed')], max_length=20, verbose_name='Transaction Type')),
                ('CrdTrnsTransactionDate', models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date')),
            ],
            options={
                'verbose_name': 'Card Transaction',
                'verbose_name_plural': 'Card Transactions',
            },
        ),
        migrations.CreateModel(
            name='CumulativePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CmltvPntsMbrCardNo', models.BigIntegerField(verbose_name='Member Card Number')),
                ('CmltvPntsBizId', models.IntegerField(verbose_name='Business ID')),
                ('LifetimeEarnedPoints', models.FloatField(default=0.0)),
                ('LifetimeRedeemedPoints', models.FloatField(default=0.0)),
                ('CurrentBalance', models.FloatField(default=0.0)),
                ('TotalPurchaseAmount', models.FloatField(default=0.0)),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BizMbrBizId', models.IntegerField(verbose_name='Business ID')),
                ('BizMbrCardNo', models.BigIntegerField(verbose_name='Member Card Number')),
                ('BizMbrIsActive', models.BooleanField(default=False, verbose_name='Is Active')),
                ('BizMbrIssueDate', models.DateTimeField(auto_now_add=True, verbose_name='Issue Date')),
                ('BizMbrValidityEnd', models.DateTimeField(blank=True, null=True, verbose_name='Validity End Date')),
                ('BizMbrRuleId', models.ForeignKey(db_column='BizMbrRuleId', on_delete=django.db.models.deletion.CASCADE, related_name='reward_rules', to='business.businessrewardrule', verbose_name='Reward Rule')),
            ],
            options={
                'verbose_name': 'Business Member',
                'verbose_name_plural': 'Business Members',
            },
        ),
    ]
