# Generated by Django 5.2 on 2025-05-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrewardrule',
            name='RewardRuleIsDefault',
            field=models.BooleanField(default=False, verbose_name='Is Default Reward Rule'),
        ),
        migrations.AddField(
            model_name='businessrewardrule',
            name='count',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
