# Generated by Django 5.2 on 2025-05-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_businessrewardrule_rewardruleisdefault_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrewardrule',
            name='RewardRuleValue',
            field=models.FloatField(blank=True, null=True, verbose_name='Reward Rule Value'),
        ),
    ]
