# Generated by Django 5.2 on 2025-06-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_businessrewardrule_rewardrulevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrewardrule',
            name='RewardRuleId',
            field=models.IntegerField(default=2, verbose_name='Rule ID'),
            preserve_default=False,
        ),
    ]
