# Generated by Django 5.2 on 2025-06-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_businessrewardrule_rewardruleid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessrewardrule',
            name='RewardRuleId',
        ),
    ]
