# Generated by Django 5.2 on 2025-06-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_remove_businessrewardrule_rewardruleid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.IntegerField(verbose_name='Business ID')),
                ('card_number', models.BigIntegerField(verbose_name='Member Card Number')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
