# Generated by Django 5.2 on 2025-05-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveyanswer_surveysubmission_delete_surveyresponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysubmission',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
