# Generated by Django 5.2 on 2025-05-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_surveysubmission_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='surveysubmission',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='surveysubmission',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
