# Generated by Django 5.2 on 2025-05-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_surveysubmission_questions_delete_surveyanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysubmission',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
